version: "2"
checks:
  similar-code:
    enabled: false
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
      tests_patterns:
        - src/**/test/**
  pmd:
    enabled: true
  markdownlint:
    enabled: true
exclude_patterns:
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/*Application.java"
