server:
  port: 8080
pci-gateway:
  redirect-url: ENC(yourencryptedvalue)
  gateway-clients:
    -
      merchant-id: A
      hash-key: B
      gateway-hash-key: C
  api-url: ENC(yourencryptedvalue)
  gateway-rest-clients:
    -
      merchant-id: A
      api-key: B
      gateway-api-key: C

jasypt:
  encryptor:
    password: ${ENC_PASSWORD}

# to enable log files, comment out the following logging object and configure the path

#logging:
#  path: ./logs

# To enable splunk, just comment out the following splunk object and configure url, token and source

#splunk:
#  url: http://localhost:8080
#  token: token
#  source: pci-gateway
